const fs = require('fs');
const source = fs.readFileSync('static/app.js', 'utf8');
const match = source.match(/function profilingFieldOptions\(key,options\)\{[^\n]+\}/);
if (!match) throw new Error('profilingFieldOptions was not found');
const state = {profile: {phase2: [{coverage_level: 'National'}, {coverage_level: ''}]}};
const chartValues = value => Array.isArray(value) ? value : String(value || '').split(/\s*[;,\n]\s*/).filter(Boolean);
const multiValueKey = value => String(value || '').trim().toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
eval(`${match[0]}; globalThis.testProfilingFieldOptions = profilingFieldOptions`);
const choices = globalThis.testProfilingFieldOptions('coverage_level', ['', 'National', 'State', 'County']);
if (choices[0] !== '') throw new Error('Blank dropdown option was removed');
if (choices.filter(value => value === 'National').length !== 1) throw new Error('Dropdown choices were not deduplicated');
const entryMatch = source.match(/function entryControl\(attr,key,type,options,value\)\{[^\n]+\}/);
if (!entryMatch) throw new Error('entryControl was not found');
const escapeHtml = value => String(value ?? '');
const multiControl = () => '';
eval(`${entryMatch[0]}; globalThis.testEntryControl = entryControl`);
const html = globalThis.testEntryControl('p2', 'coverage_level', 'select', choices, '');
if (!html.includes('value="" selected>No response</option>')) throw new Error('Blank coverage is not rendered as a selected No response option');
if (/value="National" selected/.test(html)) throw new Error('National was selected for a blank coverage response');
console.log('PASS: unanswered Profiling dropdowns display No response and retain an empty value');
